# Generated by Django 6.0.2 on 2026-03-19 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100)),
                ("category_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=250)),
                ("event_description", models.CharField(max_length=250)),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=250)),
                ("required_volunteers", models.CharField(max_length=250)),
                ("created_by", models.CharField(max_length=250)),
                ("event_status", models.CharField(max_length=250)),
                ("is_active", models.CharField(max_length=250)),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
                (
                    "event_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer", models.CharField(max_length=250)),
                ("check_in_time", models.DateTimeField()),
                ("check_out_time", models.DateTimeField()),
                ("total_hours", models.IntegerField()),
                ("attendance_status", models.CharField(max_length=50)),
                ("verified_by", models.CharField(max_length=250)),
                ("is_active", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminapp.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_name", models.CharField(max_length=250)),
                ("role_description", models.CharField(max_length=250)),
                ("required_count", models.IntegerField()),
                ("is_active", models.CharField(max_length=250)),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminapp.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer", models.CharField(max_length=250)),
                ("assigned_role", models.CharField(max_length=250)),
                ("assigned_by", models.CharField(max_length=250)),
                ("task_status", models.CharField(max_length=250)),
                ("assigned_date", models.DateField()),
                ("completed_date", models.DateField()),
                ("remarks", models.CharField(max_length=250)),
                ("is_active", models.CharField(max_length=10)),
                ("created_at", models.DateField()),
                ("updated_at", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminapp.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer", models.CharField(max_length=250)),
                ("preferred_role", models.CharField(max_length=250)),
                ("application_status", models.CharField(max_length=250)),
                ("admin_remark", models.CharField(max_length=250)),
                ("is_active", models.CharField(max_length=250)),
                ("applied_at", models.DateField()),
                ("updated_at", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminapp.event"
                    ),
                ),
            ],
        ),
    ]
