# Generated by Django 6.0.2 on 2026-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="eventrole",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="eventrole",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="taskassignment",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="applied_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="updated_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
