# Generated by Django 6.0.2 on 2026-04-13 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_event_created_at_alter_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.volunteerapplication'),
        ),
    ]
