# Generated by Django 6.0.2 on 2026-04-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_taskassignment_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='volunteer',
            new_name='volunter',
        ),
    ]
