# Generated by Django 6.0.2 on 2026-04-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_volunteer_taskassignment_volunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='payment_amount',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'Cash'), ('UPI', 'UPI')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
