# Generated by Django 6.0.2 on 2026-04-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_taskassignment_paid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskassignment',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='payment_status',
        ),
    ]
