# Generated by Django 6.0.2 on 2026-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0006_remove_taskassignment_paid_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
