# Generated by Django 6.0.2 on 2026-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_event_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='eventrole'),
        ),
    ]
