# Generated by Django 6.0.2 on 2026-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("Upcoming", "Upcoming"),
                    ("In Process", "In Process"),
                    ("Completed", "Completed"),
                    ("Delayed", "Delayed"),
                ],
                default="Upcoming",
                max_length=20,
            ),
        ),
    ]
