# Generated by Django 6.0.2 on 2026-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_booking_process_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
